service: coffee-cake-api
app: coffee-cake-api
tenant: stream

frameworkVersion: '>=1.32.0 <2.0.0'

provider:
    name: aws
    runtime: nodejs8.10
    stage: prod
    region: us-east-1
    memorySize: 3008
    environment:
        DB_URI: YOUR_MONGODB_URI
        DB_NAME: YOUR_MONGODB_DB_NAME
        STREAM_ID: YOUR_STREAM_APP_ID
        STREAM_KEY: YOUR_STREAM_API_KEY
        STREAM_SECRET: YOUR_STREAM_API_SECRET

functions:
    signup:
        handler: handler.signup
        events:
            - http:
                  path: /signup
                  method: post
                  cors: true
    signin:
        handler: handler.signin
        events:
            - http:
                  path: /signin
                  method: post
                  cors: true
    suggested:
        handler: handler.suggested
        events:
            - http:
                  path: /suggested
                  method: get
                  cors: true

plugins:
    - serverless-offline
    - serverless-webpack

custom:
    webpack:
        packager: 'yarn'
        webpackConfig: 'webpack.config.js'
        includeModules: true
    serverless-offline:
        port: 8000
